# Generated by Django 4.0.8 on 2023-05-18 09:03

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(default=catalog.models.get_default_image, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default=catalog.models.get_default_image, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=catalog.models.get_default_image, null=True, upload_to='images/'),
        ),
    ]
