# Generated by Django 4.0.8 on 2023-05-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_author_image_alter_book_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
